### ISSUE TITLE
Doesn't work, leaks.

### ISSUE THREAD

**Issue by joeyhub** [roribio/alpine-sqs#33]
Even when configured for local it tries to shoot out onto the internet...

```
{ UnknownEndpoint: Inaccessible host: `sqs.local.amazonaws.com'. This service may not be available in the `local' region.
    at Request.ENOTFOUND_ERROR (/opt/sqs-insight/node_modules/aws-sdk/lib/event_listeners.js:494:46)
    at Request.callListeners (/opt/sqs-insight/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/opt/sqs-insight/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/sqs-insight/node_modules/aws-sdk/lib/request.js:683:14)
    at ClientRequest.error (/opt/sqs-insight/node_modules/aws-sdk/lib/event_listeners.js:333:22)
    at ClientRequest.<anonymous> (/opt/sqs-insight/node_modules/aws-sdk/lib/http/node.js:96:19)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
```

Is using SQS insight really a good idea? It hasn't been touched since 2015.

**Comment by joeyhub** [comment]
Using extra hosts to bounce it back to local seems to help.

**Comment by jackbravo** [comment]
If you check the Dockerfile, it is not using the base insight-sqs repo, but a fork that is still being maintained: https://github.com/kobim/sqs-insight

https://github.com/roribio/alpine-sqs/blob/master/Dockerfile#L15

**Comment by joeyhub** [comment]
Thanks for the redirect! I'll follow the hot potato!

**Comment by jackbravo** [comment]
That said, even the maintained version is based on Angular 1 and other really old dependencies with security issues. DO NOT USE IN PRODUCTION :-p.

**Comment by joeyhub** [comment]
Realistically speaking AWS should be shunting this so good effort trying to fill in.

**Comment by jackbravo** [comment]
Why do you think that?

**Comment by joeyhub** [comment]
Some people pay AWS a lot but to get a local test set up that's good, quick and not pulling in some test AWS setup still having metred services is more difficult than it should, AWS should give you everything that you need. It's might not be popular to say but we all know Amazon kind of sucks other than having some monopoly of sorts. That can be alright but it pushes the limits. What's having the big green continue with purchase and checkout button also replaced with actually also buy our subscription services? Mate I just wanted one bar of soap. How did that end up with a monthly charge?

AWS has some deficits. It's reached a point it can get away with anything and it maximises that to maximise profits. Not everyone minds some mutual give and take but they just want to take take take and it's really disgusting. Just walked in as a consultant for a small businesses. Drowning in AWS metered fees. What did I do? Reserve instances? Work out how things aren't on the same availability zone but sharing lots of traffic? Nah. Just switched them onto a couple of dedis dropping costs from several hundred K a year to some thousands a year then helped them hire a sysadmin to have on hand because what's 25k to 35k per year compared to AWS metered costs plus the overhead of the complexity such as you log in and it's a splat of all their services making you jump through hoops to even see what you actually have. Could be great but it's not.

Here's the thing, it's not normal OSS, we're sinking A LOT into AWS so they should be able to give some decent SQS testing containers but instead we have to rely on some volunteers doing the best with what little they have to share which often is barely enough when AWS is rolling in it mate.
